### ISSUE TITLE
Mesurement results don't showing up after update

### ISSUE THREAD

**Issue by coderDem** [IteraSpeed/OpenSpeedMonitor#13]
Hello,

I updated the project to the new stand, but all the old measurement results don't showing up.
I get the message that no data is available. It is possible to show the old results?

Beste regards
coderdem

**Comment by coderDem** [comment]
Ok I get the source of this behavior. The problem is the connectivity_profile_id. All the old event results have no connectivity_profile_id. After update all the event results with the connectivity profile id value of 1 in the database the results now showing up.

**Comment by nilskuhn** [comment]
Sorry for that.

At the moment we are working on our automated build. We will push the code with each minor release to github automatically then. New releases will be available on github then with release notes. We will add an sql script to these notes if a manual migration is necessary for older data.

**Comment by coderDem** [comment]
Are the sql scripts now available?

**Comment by nilskuhn** [comment]
Yes, they are. And even better: We integrated [Liquibase](http://www.liquibase.org/), a library for automatic schema updates.

**So, you will never have to update your osm database manually again!**

Downside is, you have to follow the steps described in [release notes for release 3.3.0](https://github.com/IteraSpeed/OpenSpeedMonitor/releases) to bring your legacy database up to the actual state, once.

**Comment by coderDem** [comment]
That is cool, but it does not work. I get this error after update to the 3.3.0 Version:

<code>         at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
        ... 17 more
context.GrailsContextLoaderListener Error initializing the application: Migration failed for change
set 2015-11-18-SCHEME-initial-liquibase.groovy::1447946152150-1::nkuhn (generated):
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE `aggregator_typ
e` (`id` BIGINT AUTO_INCREMENT NOT NULL, `version` BIGINT NOT NULL, `measurand_group` VARCHAR(255) N
OT NULL, `name` VARCHAR(255) NOT NULL, CONSTRAINT `aggregator_tyPK` PRIMARY KEY (`id`)): Table 'aggr
egator_type' already exists:
          Caused By: Error executing SQL CREATE TABLE `aggregator_type` (`id` BIGINT AUTO_INCREMENT
NOT NULL, `version` BIGINT NOT NULL, `measurand_group` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NO
T NULL, CONSTRAINT `aggregator_tyPK` PRIMARY KEY (`id`)): Table 'aggregator_type' already exists:
          Caused By: Table 'aggregator_type' already exists
liquibase.exception.MigrationFailedException: Migration failed for change set 2015-11-18-SCHEME-init
ial-liquibase.groovy::1447946152150-1::nkuhn (generated):
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE `aggregator_typ
e` (`id` BIGINT AUTO_INCREMENT NOT NULL, `version` BIGINT NOT NULL, `measurand_group` VARCHAR(255) N
OT NULL, `name` VARCHAR(255) NOT NULL, CONSTRAINT `aggregator_tyPK` PRIMARY KEY (`id`)): Table 'aggr
egator_type' already exists:
          Caused By: Error executing SQL CREATE TABLE `aggregator_type` (`id` BIGINT AUTO_INCREMENT
NOT NULL, `version` BIGINT NOT NULL, `measurand_group` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NO
T NULL, CONSTRAINT `aggregator_tyPK` PRIMARY KEY (`id`)): Table 'aggregator_type' already exists:
          Caused By: Table 'aggregator_type' already exists
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:347)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:27)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:58)
        at liquibase.Liquibase.update(Liquibase.java:114)
        at grails.plugin.databasemigration.MigrationRunner$_runMigrations_closure2.doCall(MigrationR
unner.groovy:117)
        at grails.plugin.databasemigration.MigrationRunner.runMigrations(MigrationRunner.groovy:109)

        at grails.plugin.databasemigration.MigrationRunner$_autoRun_closure1.doCall(MigrationRunner.
groovy:76)
        at grails.plugin.databasemigration.MigrationUtils.executeInSession(MigrationUtils.groovy:133
)
        at grails.plugin.databasemigration.MigrationRunner.autoRun(MigrationRunner.groovy:56)
        at DatabaseMigrationGrailsPlugin$_closure2.doCall(DatabaseMigrationGrailsPlugin.groovy:96)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE `aggregator_type`
 (`id` BIGINT AUTO_INCREMENT NOT NULL, `version` BIGINT NOT NULL, `measurand_group` VARCHAR(255) NOT
 NULL, `name` VARCHAR(255) NOT NULL, CONSTRAINT `aggregator_tyPK` PRIMARY KEY (`id`)): Table 'aggreg
ator_type' already exists
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:62)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:104)
        at liquibase.database.AbstractDatabase.execute(AbstractDatabase.java:1091)
        at liquibase.database.AbstractDatabase.executeStatements(AbstractDatabase.java:1075)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:317)
        ... 13 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'aggregator_type' alread
y exists
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4190)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4122)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2570)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2731)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2812)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2761)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:894)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:732)
        at liquibase.executor.jvm.JdbcExecutor$1ExecuteStatementCallback.doInStatement(JdbcExecutor.
java:92)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
        ... 17 more
context.GrailsContextLoaderListener Error initializing Grails: Migration failed for change set 2015-
11-18-SCHEME-initial-liquibase.groovy::1447946152150-1::nkuhn (generated):
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE `aggregator_typ
e` (`id` BIGINT AUTO_INCREMENT NOT NULL, `version` BIGINT NOT NULL, `measurand_group` VARCHAR(255) N
OT NULL, `name` VARCHAR(255) NOT NULL, CONSTRAINT `aggregator_tyPK` PRIMARY KEY (`id`)): Table 'aggr
egator_type' already exists:
          Caused By: Error executing SQL CREATE TABLE `aggregator_type` (`id` BIGINT AUTO_INCREMENT
NOT NULL, `version` BIGINT NOT NULL, `measurand_group` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NO
T NULL, CONSTRAINT `aggregator_tyPK` PRIMARY KEY (`id`)): Table 'aggregator_type' already exists:
          Caused By: Table 'aggregator_type' already exists
liquibase.exception.MigrationFailedException: Migration failed for change set 2015-11-18-SCHEME-init
ial-liquibase.groovy::1447946152150-1::nkuhn (generated):
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE `aggregator_typ
e` (`id` BIGINT AUTO_INCREMENT NOT NULL, `version` BIGINT NOT NULL, `measurand_group` VARCHAR(255) N
OT NULL, `name` VARCHAR(255) NOT NULL, CONSTRAINT `aggregator_tyPK` PRIMARY KEY (`id`)): Table 'aggr
egator_type' already exists:
          Caused By: Error executing SQL CREATE TABLE `aggregator_type` (`id` BIGINT AUTO_INCREMENT
NOT NULL, `version` BIGINT NOT NULL, `measurand_group` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NO
T NULL, CONSTRAINT `aggregator_tyPK` PRIMARY KEY (`id`)): Table 'aggregator_type' already exists:
          Caused By: Table 'aggregator_type' already exists
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:347)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:27)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:58)
        at liquibase.Liquibase.update(Liquibase.java:114)
        at grails.plugin.databasemigration.MigrationRunner$_runMigrations_closure2.doCall(MigrationR
unner.groovy:117)
        at grails.plugin.databasemigration.MigrationRunner.runMigrations(MigrationRunner.groovy:109)

        at grails.plugin.databasemigration.MigrationRunner$_autoRun_closure1.doCall(MigrationRunner.
groovy:76)
        at grails.plugin.databasemigration.MigrationUtils.executeInSession(MigrationUtils.groovy:133
)
        at grails.plugin.databasemigration.MigrationRunner.autoRun(MigrationRunner.groovy:56)
        at DatabaseMigrationGrailsPlugin$_closure2.doCall(DatabaseMigrationGrailsPlugin.groovy:96)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE `aggregator_type`
 (`id` BIGINT AUTO_INCREMENT NOT NULL, `version` BIGINT NOT NULL, `measurand_group` VARCHAR(255) NOT
 NULL, `name` VARCHAR(255) NOT NULL, CONSTRAINT `aggregator_tyPK` PRIMARY KEY (`id`)): Table 'aggreg
ator_type' already exists
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:62)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:104)
        at liquibase.database.AbstractDatabase.execute(AbstractDatabase.java:1091)
        at liquibase.database.AbstractDatabase.executeStatements(AbstractDatabase.java:1075)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:317)
        ... 13 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'aggregator_type' alread
y exists
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4190)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4122)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2570)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2731)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2812)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2761)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:894)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:732)
        at liquibase.executor.jvm.JdbcExecutor$1ExecuteStatementCallback.doInStatement(JdbcExecutor.
java:92)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
        ... 17 more
Exception sending context initialized event to listener instance of class org.codehaus.groovy.grails
.web.context.GrailsContextLoaderListener
org.springframework.beans.factory.access.BootstrapException: Error executing bootstraps; nested exce
ption is liquibase.exception.MigrationFailedException: Migration failed for change set 2015-11-18-SC
HEME-initial-liquibase.groovy::1447946152150-1::nkuhn (generated):
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE `aggregator_typ
e` (`id` BIGINT AUTO_INCREMENT NOT NULL, `version` BIGINT NOT NULL, `measurand_group` VARCHAR(255) N
OT NULL, `name` VARCHAR(255) NOT NULL, CONSTRAINT `aggregator_tyPK` PRIMARY KEY (`id`)): Table 'aggr
egator_type' already exists:
          Caused By: Error executing SQL CREATE TABLE `aggregator_type` (`id` BIGINT AUTO_INCREMENT
NOT NULL, `version` BIGINT NOT NULL, `measurand_group` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NO
T NULL, CONSTRAINT `aggregator_tyPK` PRIMARY KEY (`id`)): Table 'aggregator_type' already exists:
          Caused By: Table 'aggregator_type' already exists
        at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationCont
ext(GrailsContextLoaderListener.java:126)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderLis
tener.java:106)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set 2015-11-18-
SCHEME-initial-liquibase.groovy::1447946152150-1::nkuhn (generated):
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE `aggregator_typ
e` (`id` BIGINT AUTO_INCREMENT NOT NULL, `version` BIGINT NOT NULL, `measurand_group` VARCHAR(255) N
OT NULL, `name` VARCHAR(255) NOT NULL, CONSTRAINT `aggregator_tyPK` PRIMARY KEY (`id`)): Table 'aggr
egator_type' already exists:
          Caused By: Error executing SQL CREATE TABLE `aggregator_type` (`id` BIGINT AUTO_INCREMENT
NOT NULL, `version` BIGINT NOT NULL, `measurand_group` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NO
T NULL, CONSTRAINT `aggregator_tyPK` PRIMARY KEY (`id`)): Table 'aggregator_type' already exists:
          Caused By: Table 'aggregator_type' already exists
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:347)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:27)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:58)
        at liquibase.Liquibase.update(Liquibase.java:114)
        at grails.plugin.databasemigration.MigrationRunner$_runMigrations_closure2.doCall(MigrationR
unner.groovy:117)
        at grails.plugin.databasemigration.MigrationRunner.runMigrations(MigrationRunner.groovy:109)

        at grails.plugin.databasemigration.MigrationRunner$_autoRun_closure1.doCall(MigrationRunner.
groovy:76)
        at grails.plugin.databasemigration.MigrationUtils.executeInSession(MigrationUtils.groovy:133
)
        at grails.plugin.databasemigration.MigrationRunner.autoRun(MigrationRunner.groovy:56)
        at DatabaseMigrationGrailsPlugin$_closure2.doCall(DatabaseMigrationGrailsPlugin.groovy:96)
        ... 4 more
Caused by: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE `aggregator_type`
 (`id` BIGINT AUTO_INCREMENT NOT NULL, `version` BIGINT NOT NULL, `measurand_group` VARCHAR(255) NOT
 NULL, `name` VARCHAR(255) NOT NULL, CONSTRAINT `aggregator_tyPK` PRIMARY KEY (`id`)): Table 'aggreg
ator_type' already exists
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:62)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:104)
        at liquibase.database.AbstractDatabase.execute(AbstractDatabase.java:1091)
        at liquibase.database.AbstractDatabase.executeStatements(AbstractDatabase.java:1075)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:317)
        ... 13 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'aggregator_type' alread
y exists
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4190)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4122)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2570)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2731)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2812)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2761)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:894)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:732)
        at liquibase.executor.jvm.JdbcExecutor$1ExecuteStatementCallback.doInStatement(JdbcExecutor.
java:92)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
        ... 17 more
Error listenerStart
Context [/OpenSpeedMonitor] startup failed due to previous errors
The web application [/OpenSpeedMonitor] registered the JDBC driver [org.h2.Driver] but failed to unr
egister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been
forcibly unregistered.
The web application [/OpenSpeedMonitor] registered the JDBC driver [com.p6spy.engine.spy.P6SpyDriver
] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JD
BC Driver has been forcibly unregistered.
The web application [/OpenSpeedMonitor] registered the JDBC driver [com.mysql.jdbc.Driver] but faile
d to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver h
as been forcibly unregistered. </code>

Any idea why this happening?

**Comment by nilskuhn** [comment]
Which steps of section _Initially update legacy database_ of [release notes v3.3.0](https://github.com/IteraSpeed/OpenSpeedMonitor/releases) you have realized. Or, to be more precise, in which step you get that error message?

Looks like you started OSM version 3.3.0 without updating your legacy database before. That doesn't work with a legacy database. 

I would recommend (like described in release notes) to **dump your database** before update it.

**Comment by coderDem** [comment]
I tried to follow the instruction, but I get this error-message for the first step:
<code>| Error Could not checkout tag for Grails release [3.0.9]: Checkout conflict with files:
README.md
profiles/base/profile.yml
profiles/base/skeleton/build.gradle
profiles/base/skeleton/gradle.properties
profiles/base/skeleton/gradle/wrapper/gradle-wrapper.jar
profiles/base/skeleton/gradle/wrapper/gradle-wrapper.properties
profiles/base/skeleton/gradlew
profiles/base/skeleton/grails-app/i18n/messages.properties
profiles/plugin/profile.yml
profiles/plugin/skeleton/build.gradle
profiles/web-api/profile.yml
profiles/web-api/skeleton/grails-app/controllers/UrlMappings.groovy
profiles/web-api/templates/artifacts/scaffolding/Controller.groovy
profiles/web-plugin/profile.yml
profiles/web/profile.yml
profiles/web/skeleton/grails-app/conf/application.yml (Use --stacktrace to see the full trace)
| Error Error occurred running Grails CLI: No profile found for name [web]. (Use --stacktrace to see
 the full trace) </code>

**Comment by nilskuhn** [comment]
Which grails version you are using? We are not on version 3 at the moment. Looks like you tried to run OpenSpeedMonitor with grails version 3.
You are save to use the right version if you just use the grails wrapper at project root `./grailsw`.
